from Classe_Python_MySQL_Estrutura_Dados import *

bd = Classe_Python_MySQL_Estrutura_Dados(servidor='localhost',
                                         utilizador='root',
                                         password='root',
                                         base_dados='basedadoslabaguas')
bd.ListTables()
bd.TableStrucure('cliente')
bd.ListDataTable('cliente')

bd.ListTablesAndStructure()
bd.ListTablesData()

# List of tables --------------------
# Table  ('analise',)
# Table  ('analiseparametro',)
# Table  ('analiseresultado',)
# Table  ('cliente',)
# Table  ('parametro',)
# Table  ('pedidoanalise',)
# Table  ('pedidoanaliseresultado',)
# Table  ('tipocliente',)
# Tabela --------------------cliente
# ['Field', 'Type', 'Null', 'Key', 'Default', 'Extra']
# ('IDCliente', 'int', 'NO', 'PRI', None, 'auto_increment')
# ('IDTipoClienteFK', 'int', 'NO', 'MUL', None, '')
# ('Cliente', 'varchar(100)', 'NO', '', None, '')
# ('Email', 'varchar(50)', 'NO', 'UNI', None, '')
# ('Telefone', 'varchar(15)', 'NO', 'UNI', None, '')
# ('Telemovel', 'varchar(15)', 'NO', 'UNI', None, '')
# ('NIF', 'varchar(10)', 'NO', 'UNI', None, '')
# ('Morada', 'varchar(100)', 'NO', '', None, '')
# ('CodigoPostal', 'varchar(8)', 'NO', '', None, '')
# ('Localidade', 'varchar(100)', 'NO', '', None, '')
# ('Logotipo', 'blob', 'YES', '', None, '')
# ['IDCliente', 'IDTipoClienteFK', 'Cliente', 'Email', 'Telefone', 'Telemovel', 'NIF', 'Morada', 'CodigoPostal', 'Localidade', 'Logotipo']
# (1, 1, 'Fábrica Tavares', 'f.tavares@gmail.pt', '271300400', '957468904', '500400200', 'Quintazinha', '6300-666', 'GUARDA', None)
# (2, 4, 'Junta de Freguesia da Guarda', 'geral@freguesiadaguarda.pt', '271213150', '967460904', '501300400', 'Rua General Póvoas, n.º 3 -Solar dos Póvoas', '6300-714', 'GUARDA', None)
# List of tables --------------------
# Table  ('analise',)
# Tabela --------------------analise
# ['Field', 'Type', 'Null', 'Key', 'Default', 'Extra']
# ('IDAnalise', 'int', 'NO', 'PRI', None, 'auto_increment')
# ('Analise', 'varchar(100)', 'NO', '', None, '')
# ('Preco', 'decimal(10,2)', 'NO', '', '0.00', '')
# Table  ('analiseparametro',)
# Tabela --------------------analiseparametro
# ['Field', 'Type', 'Null', 'Key', 'Default', 'Extra']
# ('IDAnaliseParametro', 'int', 'NO', 'PRI', None, 'auto_increment')
# ('IDAnaliseFK', 'int', 'NO', 'MUL', None, '')
# ('IDParametroFK', 'int', 'NO', 'MUL', None, '')
# ('ValorMin', 'decimal(10,3)', 'NO', '', None, '')
# ('ValorMax', 'decimal(10,3)', 'NO', '', None, '')
# Table  ('analiseresultado',)
# Tabela --------------------analiseresultado
# ['Field', 'Type', 'Null', 'Key', 'Default', 'Extra']
# ('IDAnaliseResultado', 'int', 'NO', 'PRI', None, 'auto_increment')
# ('AnaliseResultado', 'varchar(500)', 'NO', '', None, '')
# ('IDAnaliseFK', 'int', 'NO', 'MUL', None, '')
# Table  ('cliente',)
# Tabela --------------------cliente
# ['Field', 'Type', 'Null', 'Key', 'Default', 'Extra']
# ('IDCliente', 'int', 'NO', 'PRI', None, 'auto_increment')
# ('IDTipoClienteFK', 'int', 'NO', 'MUL', None, '')
# ('Cliente', 'varchar(100)', 'NO', '', None, '')
# ('Email', 'varchar(50)', 'NO', 'UNI', None, '')
# ('Telefone', 'varchar(15)', 'NO', 'UNI', None, '')
# ('Telemovel', 'varchar(15)', 'NO', 'UNI', None, '')
# ('NIF', 'varchar(10)', 'NO', 'UNI', None, '')
# ('Morada', 'varchar(100)', 'NO', '', None, '')
# ('CodigoPostal', 'varchar(8)', 'NO', '', None, '')
# ('Localidade', 'varchar(100)', 'NO', '', None, '')
# ('Logotipo', 'blob', 'YES', '', None, '')
# Table  ('parametro',)
# Tabela --------------------parametro
# ['Field', 'Type', 'Null', 'Key', 'Default', 'Extra']
# ('IDParametro', 'int', 'NO', 'PRI', None, 'auto_increment')
# ('Parametro', 'varchar(100)', 'NO', '', None, '')
# ('ValorMin', 'decimal(10,3)', 'NO', '', None, '')
# ('ValorMax', 'decimal(10,3)', 'NO', '', None, '')
# ('Unidade', 'varchar(20)', 'NO', '', None, '')
# ('Simbolo', 'varchar(10)', 'NO', '', None, '')
# ('Observacoes', 'varchar(100)', 'NO', '', None, '')
# Table  ('pedidoanalise',)
# Tabela --------------------pedidoanalise
# ['Field', 'Type', 'Null', 'Key', 'Default', 'Extra']
# ('IDPedidoAnalise', 'int', 'NO', 'PRI', None, 'auto_increment')
# ('IDClienteFK', 'int', 'NO', 'MUL', None, '')
# ('IDAnaliseFK', 'int', 'NO', 'MUL', None, '')
# ('Data', 'datetime', 'NO', '', 'CURRENT_TIMESTAMP', 'DEFAULT_GENERATED')
# ('DataPrevista', 'datetime', 'NO', '', '(now() + interval 7 day)', 'DEFAULT_GENERATED')
# ('DataEfetiva', 'datetime', 'YES', '', None, '')
# Table  ('pedidoanaliseresultado',)
# Tabela --------------------pedidoanaliseresultado
# ['Field', 'Type', 'Null', 'Key', 'Default', 'Extra']
# ('IDPedidoAnaliseResultado', 'int', 'NO', 'PRI', None, 'auto_increment')
# ('IDPedidoAnaliseFK', 'int', 'NO', 'MUL', None, '')
# ('IDAnaliseResultadoFK', 'int', 'NO', 'MUL', None, '')
# Table  ('tipocliente',)
# Tabela --------------------tipocliente
# ['Field', 'Type', 'Null', 'Key', 'Default', 'Extra']
# ('IDTipoCliente', 'int', 'NO', 'PRI', None, 'auto_increment')
# ('TipoCliente', 'varchar(50)', 'NO', '', None, '')
# List of tables --------------------
# TABLE -------------------- ('analise',)
# ['IDAnalise', 'Analise', 'Preco']
# (1, 'Consumo humano', Decimal('65.00'))
# (2, 'Água marina e análise de sedimentos marinhos', Decimal('40.00'))
# (3, 'Efluentes industriais', Decimal('60.00'))
# (4, 'Qualidade de água subterrânea', Decimal('45.45'))
# (5, 'Caracterização e análise de águas residuais', Decimal('44.00'))
# (6, 'Estudos de rendimentos de estações de tratamento', Decimal('70.00'))
# (7, 'Águas regeneradas', Decimal('34.50'))
# (8, 'Campanhas de encaminhamentos de efluentes', Decimal('75.26'))
# (9, 'Águas de processo', Decimal('18.60'))
# (22, 'Água de torneira', Decimal('35.00'))
# (23, 'Água pré-potável', Decimal('40.00'))
# (24, 'Água natural e continental', Decimal('78.00'))
# (25, 'Água marina e análise de sedimentos marinhos', Decimal('520.00'))
# (213, 'Radioatividade em amostras de água de consumo humano', Decimal('1700.00'))
# (214, 'Legionella por PCR', Decimal('256.00'))
# (215, 'Pesticidas com mais de 400 substâncias', Decimal('320.00'))
# (216, 'Físico-química, microbiológica e organolética', Decimal('150.00'))
# (301, 'Água Potável', Decimal('40.00'))
# (302, 'Água de Poço Artesiano', Decimal('40.00'))
# (303, 'Água para Hemodiálise', Decimal('40.00'))
# (304, 'Água para Materiais Médicos (CME)', Decimal('40.00'))
# (305, 'Água Mineral', Decimal('40.00'))
# (306, 'Água Purificada', Decimal('40.00'))
# (307, 'Água de Piscina', Decimal('40.00'))
# (308, 'Legionella', Decimal('40.00'))
# TABLE -------------------- ('analiseparametro',)
# ['IDAnaliseParametro', 'IDAnaliseFK', 'IDParametroFK', 'ValorMin', 'ValorMax']
# (1, 1, 1, Decimal('0.000'), Decimal('200.000'))
# (2, 1, 2, Decimal('0.000'), Decimal('0.500'))
# (3, 1, 3, Decimal('0.000'), Decimal('0.000'))
# (4, 1, 4, Decimal('0.000'), Decimal('250.000'))
# (5, 1, 5, Decimal('0.000'), Decimal('0.000'))
# (6, 1, 6, Decimal('0.000'), Decimal('20.000'))
# (7, 1, 7, Decimal('0.000'), Decimal('2500.000'))
# (8, 1, 8, Decimal('0.000'), Decimal('0.000'))
# (9, 1, 9, Decimal('6.500'), Decimal('9.000'))
# (10, 1, 10, Decimal('0.000'), Decimal('200.000'))
# (11, 1, 11, Decimal('0.000'), Decimal('0.000'))
# (12, 1, 12, Decimal('0.000'), Decimal('50.000'))
# (13, 1, 13, Decimal('0.000'), Decimal('1.000'))
# (14, 1, 14, Decimal('0.000'), Decimal('3.000'))
# (15, 1, 15, Decimal('0.000'), Decimal('5.000'))
# (16, 1, 16, Decimal('0.000'), Decimal('250.000'))
# (17, 1, 17, Decimal('0.000'), Decimal('200.000'))
# (18, 1, 18, Decimal('0.000'), Decimal('3.000'))
# (19, 1, 19, Decimal('0.000'), Decimal('0.000'))
# (20, 1, 20, Decimal('0.000'), Decimal('0.000'))
# (21, 1, 21, Decimal('0.000'), Decimal('0.000'))
# (22, 1, 22, Decimal('0.000'), Decimal('0.000'))
# (23, 1, 23, Decimal('0.000'), Decimal('4.000'))
# (24, 1, 24, Decimal('0.000'), Decimal('0.500'))
# (25, 1, 25, Decimal('0.000'), Decimal('1.000'))
# (26, 1, 26, Decimal('0.000'), Decimal('100.000'))
# (27, 1, 27, Decimal('0.000'), Decimal('0.000'))
# (28, 1, 28, Decimal('0.000'), Decimal('0.000'))
# TABLE -------------------- ('analiseresultado',)
# ['IDAnaliseResultado', 'AnaliseResultado', 'IDAnaliseFK']
# (1, 'Própria para consumo', 1)
# (2, 'Imprópria para consumo', 1)
# TABLE -------------------- ('cliente',)
# ['IDCliente', 'IDTipoClienteFK', 'Cliente', 'Email', 'Telefone', 'Telemovel', 'NIF', 'Morada', 'CodigoPostal', 'Localidade', 'Logotipo']
# (1, 1, 'Fábrica Tavares', 'f.tavares@gmail.pt', '271300400', '957468904', '500400200', 'Quintazinha', '6300-666', 'GUARDA', None)
# (2, 4, 'Junta de Freguesia da Guarda', 'geral@freguesiadaguarda.pt', '271213150', '967460904', '501300400', 'Rua General Póvoas, n.º 3 -Solar dos Póvoas', '6300-714', 'GUARDA', None)
# TABLE -------------------- ('parametro',)
# ['IDParametro', 'Parametro', 'ValorMin', 'ValorMax', 'Unidade', 'Simbolo', 'Observacoes']
# (1, 'Alumínio', Decimal('0.000'), Decimal('200.000'), 'μg/l', 'Al', '')
# (2, 'Amónio', Decimal('0.000'), Decimal('0.500'), 'mg/l', 'NH4', '')
# (3, 'Cálcio', Decimal('0.000'), Decimal('0.000'), 'mg/l', 'Ca', 'Vn1 , 2 e 5.')
# (4, 'Cloretos', Decimal('0.000'), Decimal('250.000'), ' mg/l', 'Cl', 'Vn1.')
# (5, 'Clostridium perfringens (incluindo esporos)', Decimal('0.000'), Decimal('0.000'), 'N/100 ml', '', 'Vn6.')
# (6, 'Cor', Decimal('0.000'), Decimal('20.000'), ' mg/l', ' PtCo', '')
# (7, 'Condutividade', Decimal('0.000'), Decimal('2500.000'), 'μS/cma 20°C', '', 'Vn1.')
# (8, 'Dureza total', Decimal('0.000'), Decimal('0.000'), ' mg/l', 'CaCO3', 'Vn1, 4 e 5.')
# (9, 'pH', Decimal('6.500'), Decimal('9.000'), 'unidades de pH', 'pH', 'Vn1 e 7.')
# (10, 'Ferro', Decimal('0.000'), Decimal('200.000'), 'μg/l', 'Fe', '')
# (11, 'Magnésio', Decimal('0.000'), Decimal('0.000'), 'mg/l', 'Mg', 'Vn1, 3 e 5.')
# (12, 'Manganês', Decimal('0.000'), Decimal('50.000'), ' μg/l', 'Mn', '')
# (13, 'Microcistinas LR total', Decimal('0.000'), Decimal('1.000'), 'μg/l', '', 'Vn16.')
# (14, 'Cheiro a 25°C', Decimal('0.000'), Decimal('3.000'), ' Factor de diluição', '', '')
# (15, 'Oxidabilidade', Decimal('0.000'), Decimal('5.000'), 'mg/l', 'O2', 'Vn8.')
# (16, 'Sulfatos', Decimal('0.000'), Decimal('250.000'), ' mg/l', 'SO4', 'Vn1.')
# (17, 'Sódio', Decimal('0.000'), Decimal('200.000'), ' mg/l', 'Na', '')
# (18, 'Sabor a 25°C', Decimal('0.000'), Decimal('3.000'), ' Factor de diluição', '', '')
# (19, 'Número de colónias', Decimal('0.000'), Decimal('0.000'), 'N/ml a 22°C', '', 'Sem alteração anormal:Vn17 e 18.')
# (20, 'Número de colónias', Decimal('0.000'), Decimal('0.000'), 'N/ml a 37°C', '', 'Sem alteração anormal: Vn17 e 18.')
# (21, 'Bactérias coliformes', Decimal('0.000'), Decimal('0.000'), 'N/100', 'ml', 'Vn9.')
# (22, 'Carbono orgânico total (COT)', Decimal('0.000'), Decimal('0.000'), 'mg/l', 'C', 'Sem alteração anormal. Vn10 e 18')
# (23, 'Turvação', Decimal('0.000'), Decimal('4.000'), 'UNT', '', 'Vn11.')
# (24, 'α-total', Decimal('0.000'), Decimal('0.500'), 'Bq/l', '', 'Vn12 e 14.')
# (25, 'β-total', Decimal('0.000'), Decimal('1.000'), 'Bq/l', '', 'Vn12 e 14.')
# (26, 'Trítio', Decimal('0.000'), Decimal('100.000'), 'Bq/l', '', 'Vn12 e 14.')
# (27, 'Dose indicativa total', Decimal('0.000'), Decimal('0.000'), '10', 'mSv/ano', 'Vn13, 14 e 15.')
# (28, 'Desinfectante residual', Decimal('0.000'), Decimal('0.000'), ' mg/l', '', 'Vn19.')
# TABLE -------------------- ('pedidoanalise',)
# ['IDPedidoAnalise', 'IDClienteFK', 'IDAnaliseFK', 'Data', 'DataPrevista', 'DataEfetiva']
# (1, 1, 1, datetime.datetime(2024, 2, 14, 10, 41, 21), datetime.datetime(2024, 2, 21, 10, 41, 21), None)
# (2, 2, 1, datetime.datetime(2024, 2, 14, 10, 41, 21), datetime.datetime(2024, 2, 21, 10, 41, 21), None)
# TABLE -------------------- ('pedidoanaliseresultado',)
# ['IDPedidoAnaliseResultado', 'IDPedidoAnaliseFK', 'IDAnaliseResultadoFK']
# (1, 1, 1)
# (2, 2, 2)
# TABLE -------------------- ('tipocliente',)
# ['IDTipoCliente', 'TipoCliente']
# (1, 'Empresa')
# (2, 'Particular')
# (3, 'Municipios')
# (4, 'Juntas de Freguesia')
# (5, 'Restauração')
# (6, 'Saúde')
# (7, 'Alojamentos')
# (8, 'Colectividades')
# (9, 'Serviços')
# (10, 'Comércio')
# (11, 'Ensino')
# (12, 'Indústria')
